title: Michael Bowen, MSc # your name (or website title) here
logo: "/images/portfolio_img.jpg?raw=true" # your photo here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist with more than two years of experience in an analyst role, holding a Masters Degree in Data Science and a Bachelors Degree in Mathematics. <br>

  <a href="https://www.linkedin.com/in/michaelbowen7/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
